ipeer-web/grails-app/domain/ipeer/entity/Issue.groovy
package ipeer.entity

class Issue {

  String errorLog;
  String summary
  String detail
  User createdBy
  Boolean autoReported
  Date dateCreated
  Date lastUpdated

  static constraints = {
    errorLog nullable: true
  }
}

ipeer-web/grails-app/controllers/ipeer/IssueController.groovy
package ipeer

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import ipeer.entity.Issue
import ipeer.entity.Role
import ipeer.entity.User

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class IssueController {

  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
  static namespace = "front"

  def springSecurityService;

  @Secured(['ROLE_SUPER_ADMIN'])
  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    respond Issue.list(params), model: [issueInstanceCount: Issue.count()]
  }

  @Secured(['ROLE_SUPER_ADMIN'])
  def show(Issue issueInstance) {
    respond issueInstance
  }

  @Secured(['ROLE_VETERAN', 'ROLE_MENTOR'])
  def create() {
    respond new Issue(params)
  }

  @Transactional
  @Secured(['ROLE_VETERAN', 'ROLE_MENTOR'])
  def save(Issue issueInstance) {
    if (issueInstance == null) {
      notFound()
      return
    }

    issueInstance.createdBy = springSecurityService.currentUser as User
    issueInstance.autoReported = Boolean.FALSE

    if (!issueInstance.validate()) {
      respond issueInstance.errors, view: 'create'
      return
    }

    issueInstance.save flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.created.message', args: [message(code: 'issue.label', default: 'Issue'), issueInstance.id])
        redirect issueInstance
      }
      '*' { respond issueInstance, [status: CREATED] }
    }
  }

  @Secured(['ROLE_SUPER_ADMIN'])
  def edit(Issue issueInstance) {
    respond issueInstance
  }

  @Transactional
  @Secured(['ROLE_SUPER_ADMIN'])
  def update(Issue issueInstance) {
    if (issueInstance == null) {
      notFound()
      return
    }

    if (issueInstance.hasErrors()) {
      respond issueInstance.errors, view: 'edit'
      return
    }

    issueInstance.save flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.updated.message', args: [message(code: 'Issue.label', default: 'Issue'), issueInstance.id])
        redirect issueInstance
      }
      '*' { respond issueInstance, [status: OK] }
    }
  }

  @Transactional
  def delete(Issue issueInstance) {

    if (issueInstance == null) {
      notFound()
      return
    }

    issueInstance.delete flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.deleted.message', args: [message(code: 'Issue.label', default: 'Issue'), issueInstance.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NO_CONTENT }
    }
  }

  protected void notFound() {
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'issue.label', default: 'Issue'), params.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NOT_FOUND }
    }
  }
}

ipeer-web/grails-app/controllers/ipeer/webservice/IssueController.groovy
package ipeer.webservice

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import ipeer.entity.Issue
import ipeer.entity.User

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class IssueController {

  static responseFormats = ['json', 'xml']
  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
  static namespace = "webservice"

  def springSecurityService

  @Secured(['ROLE_SUPER_ADMIN'])
  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    respond Issue.list(params), [status: OK]
  }

  @Secured(['ROLE_VETERAN', 'ROLE_MENTOR'])
  def show(Issue issue) {
    respond issue
  }

  @Transactional
  @Secured(['ROLE_VETERAN', 'ROLE_MENTOR'])
  def save(Issue issueInstance) {
    if (issueInstance == null) {
      render status: NOT_FOUND
      return
    }

    issueInstance.createdBy = springSecurityService.currentUser as User
    issueInstance.autoReported = Boolean.FALSE

    if (!issueInstance.validate()) {
      render status: NOT_ACCEPTABLE
      return
    }

    issueInstance.save flush: true
    respond issueInstance, [status: CREATED]
  }

  @Transactional
  def update(Issue issueInstance) {
    if (issueInstance == null) {
      render status: NOT_FOUND
      return
    }

    issueInstance.validate()
    if (issueInstance.hasErrors()) {
      render status: NOT_ACCEPTABLE
      return
    }

    issueInstance.save flush: true
    respond issueInstance, [status: OK]
  }

  @Transactional
  def delete(Issue issueInstance) {

    if (issueInstance == null) {
      render status: NOT_FOUND
      return
    }

    issueInstance.delete flush: true
    render status: NO_CONTENT
  }
}

ipeer-web/grails-app/views/issue/_form.gsp
<%@ page import="ipeer.entity.Issue" %>


<div class="mdl-grid ${hasErrors(bean: issue, field: 'summary', 'error')} required">
  <div class="mdl-cell mdl-cell--3-col"><label for="summary">
    <g:message code="issue.summary.label" default="Summary"/>
    <span class="required-indicator">*</span>
  </label>
  </div>

  <div class="mdl-cell mdl-cell--3-col"><g:textField size="50" name="summary" required=""
                                                     value="${issue?.summary}"/>
  </div>
</div>

<div class="mdl-grid ${hasErrors(bean: issue, field: 'detail', 'error')} required">
  <div class="mdl-cell mdl-cell--3-col"><label for="detail">
    <g:message code="issue.detail.label" default="Detail"/>
    <span class="required-indicator">*</span>
  </label>
  </div>

  <div class="mdl-cell mdl-cell--3-col">
    <g:textArea name="detail" cols="50" rows="10" required="" value="${issue?.detail}"/>
  </div>
</div>


<div class="mdl-grid ${hasErrors(bean: issue, field: 'errorLog', 'error')} ">
  <div class="mdl-cell mdl-cell--3-col"><label for="errorLog">
    <g:message code="issue.errorLog.label" default="Error Log"/>
  </label>
  </div>

  <div class="mdl-cell mdl-cell--3-col">
    <g:textArea name="errorLog" cols="50" rows="10" value="${issue?.errorLog}"/>
  </div>
</div>

ipeer-web/grails-app/views/issue/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'issue.label', default: 'Issue')}"/>
  <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>


<g:form class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--8-col mdl-cell--4-col-phone mdl-cell--4-col-tablet mdl-cell--8-col-desktop"
        action="save" namespace="front" >
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.create.label" args="[entityName]"/>
  </div>

  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${issue}">
      <ul class="errors" role="alert">
      <g:eachError bean="${issue}" var="error">
        <li<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
        <g:message error="${error}"/>
        </li>
      </g:eachError>
      </ul>
    </g:hasErrors>

    <g:render template="form"/>
  </div>

  <div class="mdl-card__actions mdl-card--border">
    <g:submitButton name="create" value="${message(code: 'default.button.create.label', default: 'Create')}"
                    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white"/>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="index" namespace="front">
      Cancel
    </g:link>
  </div>
</g:form>

</body>
</html>

ipeer-web/grails-app/views/issue/edit.gsp
<%@ page import="ipeer.entity.Issue" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'issue.label', default: 'Issue')}"/>
  <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>

<g:form class="mdl-card  mdl-shadow--2dp mdl-cell mdl-cell--8-col mdl-cell--4-col-phone mdl-cell--4-col-tablet mdl-cell--8-col-desktop"
        action="update" namespace="front" resource="${issue}"
        method="PUT" >
  <g:hiddenField name="version" value="${issue?.version}"/>
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.create.label" args="[entityName]"/>
  </div>
  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${issue}">
      <ul class="errors" role="alert">
      <g:eachError bean="${issue}" var="error">
        <li<g:if
          test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
          error="${error}"/></li>
      </g:eachError>
      </ul>
    </g:hasErrors>

    <g:render template="form"/>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <g:actionSubmit class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white"
                    action="update" namespace="front" value="${message(code: 'default.button.update.label', default: 'Update')}"/>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="index" namespace="admin">
      Cancel
    </g:link>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="create" namespace="admin">
      <g:message code="default.new.label" args="[entityName]"/>
    </g:link>
  </div>
</g:form>

</body>
</html>

ipeer-web/grails-app/views/issue/index.gsp
<%@ page import="ipeer.entity.Issue" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'issue.label', default: 'Issue')}"/>
  <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-desktop  mdl-cell--8-col-tablet  mdl-cell--6-col-phone">
  <h1><g:message code="default.list.label" args="[entityName]"/></h1>
  <g:if test="${flash.message}">
    <div class="message" role="status">${flash.message}</div>
  </g:if>

  <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
    <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">
        <g:message code="issue.id.label" default="#"/>
      </th>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="errorLog"
                        title="${message(code: 'issue.errorLog.label', default: 'Error Log')}"/>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="autoReported"
                        title="${message(code: 'issue.autoReported.label', default: 'Auto Reported')}"/>
      
      <th class="mdl-data-table__cell--non-numeric">
        <g:message code="issue.createdBy.label" default="Created By"/>
      </th>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="dateCreated"
                        title="${message(code: 'issue.dateCreated.label', default: 'Date Created')}"/>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="detail"
                        title="${message(code: 'issue.detail.label', default: 'Detail')}"/>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="lastUpdated"
                        title="${message(code: 'issue.lastUpdated.label', default: 'Last Updated')}"/>
      
      <th class="mdl-data-table__cell--non-numeric">Action</th>
    </tr>
    </thead>
    <tbody>
    <g:each in="${issueList}" status="i" var="issue">
      <tr>
        <td class="mdl-data-table__cell--non-numeric">
          <g:link namespace="front" action="show" id="${issue.id}">${issue.id}</g:link>
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          ${fieldValue(bean: issue, field: "errorLog")}
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          <g:formatBoolean boolean="${issue.autoReported}"/>
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
            
            <g:link namespace="admin" controller="user" action="show" id="${issue.createdBy.id}">${issue.createdBy}</g:link>
            
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          <g:formatDate date="${issue.dateCreated}"/>
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          ${fieldValue(bean: issue, field: "detail")}
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          <g:formatDate date="${issue.lastUpdated}"/>
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
          <g:link namespace="front" action="show" id="${issue.id}"><i class="mdl-color-text--grey material-icons">description</i></g:link>
          <g:link namespace="front" action="edit" id="${issue.id}"><i class="mdl-color-text--grey material-icons">edit</i></g:link>
        </td>
      </tr>
    </g:each>
    </tbody>
  </table>

  <div class="mdl-card__actions pagination">
    <g:link action="create" namespace="front"
            class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white">
      <g:message code="default.new.label" args="[entityName]"/>
    </g:link>
    <g:paginate total="${issueCount ?: 0}"/>
  </div>
</div>
</body>
</html>

ipeer-web/grails-app/views/issue/show.gsp
<%@ page import="ipeer.entity.Issue" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'issue.label', default: 'Issue')}"/>
  <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col mdl-cell--4-col-phone">
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.show.label" args="[entityName]"/>
  </div>

  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>

    
    <g:if test="${issue?.errorLog}">
      <div class="mdl-grid">
        <div id="errorLog-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="issue.errorLog.label" default="Error Log"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="errorLog-label">
          
          <g:fieldValue bean="${issue}" field="errorLog"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${issue?.autoReported}">
      <div class="mdl-grid">
        <div id="autoReported-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="issue.autoReported.label" default="Auto Reported"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="autoReported-label">
          
          <g:formatBoolean boolean="${issue?.autoReported}"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${issue?.createdBy}">
      <div class="mdl-grid">
        <div id="createdBy-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="issue.createdBy.label" default="Created By"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="createdBy-label">
          
          <g:link controller="user" namespace="admin" action="show" id="${issue?.createdBy?.id}">${issue?.createdBy?.encodeAsHTML()}</g:link>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${issue?.dateCreated}">
      <div class="mdl-grid">
        <div id="dateCreated-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="issue.dateCreated.label" default="Date Created"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="dateCreated-label">
          
          <g:formatDate date="${issue?.dateCreated}"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${issue?.detail}">
      <div class="mdl-grid">
        <div id="detail-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="issue.detail.label" default="Detail"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="detail-label">
          
          <g:fieldValue bean="${issue}" field="detail"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${issue?.lastUpdated}">
      <div class="mdl-grid">
        <div id="lastUpdated-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="issue.lastUpdated.label" default="Last Updated"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="lastUpdated-label">
          
          <g:formatDate date="${issue?.lastUpdated}"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${issue?.summary}">
      <div class="mdl-grid">
        <div id="summary-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="issue.summary.label" default="Summary"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="summary-label">
          
          <g:fieldValue bean="${issue}" field="summary"/>
          
        </div>
      </div>
    </g:if>
    
  </div>


  <g:form class="mdl-card__actions mdl-card--border" action="delete" resource="${issue}" namespace="front" method="DELETE">
      <g:link action="edit" namespace="front" resource="${issue}"
              class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
        <g:message code="default.button.edit.label" default="Edit"/>
      </g:link>
      <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" namespace="front" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link>
      <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" namespace="front" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link>
  </g:form>
</div>

</body>
</html>