ipeer-web/grails-app/domain/ipeer/entity/SubmissionSummary.groovy
package ipeer.entity

class SubmissionSummary {

  Date submissionTime
  Integer score
  Integer progressDirection
  Schedule schedule
  Veteran veteran
  Mentor submittedBy

  static hasMany = [submittedAnswers: SubmittedAnswer]

  static constraints = {
    schedule nullable: false, unique: 'veteran'
    veteran nullable: false
    submissionTime nullable: false
    score nullable: false
    progressDirection nullable: false
    submittedBy nullable: true
  }

}

ipeer-web/grails-app/controllers/ipeer/admin/SubmissionSummaryController.groovy
package ipeer.admin

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import ipeer.entity.SubmissionSummary

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class SubmissionSummaryController {

  static namespace = "admin"
  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

  @Secured(['ROLE_SUPER_ADMIN'])
  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    respond SubmissionSummary.list(params), model: [submissionSummaryCount: SubmissionSummary.count()]
  }

  @Secured(['ROLE_MENTOR'])
  def show(SubmissionSummary submissionSummaryInstance) {
    respond submissionSummaryInstance
  }

  def create() {
    respond new SubmissionSummary(params)
  }

  @Transactional
  def save(SubmissionSummary submissionSummaryInstance) {
    if (submissionSummaryInstance == null) {
      notFound()
      return
    }

    if (submissionSummaryInstance.hasErrors()) {
      respond submissionSummaryInstance.errors, view: 'create'
      return
    }

    submissionSummaryInstance.save flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.created.message', args: [message(code: 'submissionSummary.label', default: 'SubmissionSummary'), submissionSummaryInstance.id])
        redirect submissionSummaryInstance
      }
      '*' { respond submissionSummaryInstance, [status: CREATED] }
    }
  }

  def edit(SubmissionSummary submissionSummaryInstance) {
    respond submissionSummaryInstance
  }

  @Transactional
  def update(SubmissionSummary submissionSummaryInstance) {
    if (submissionSummaryInstance == null) {
      notFound()
      return
    }

    if (submissionSummaryInstance.hasErrors()) {
      respond submissionSummaryInstance.errors, view: 'edit'
      return
    }

    submissionSummaryInstance.save flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.updated.message', args: [message(code: 'SubmissionSummary.label', default: 'SubmissionSummary'), submissionSummaryInstance.id])
        redirect submissionSummaryInstance
      }
      '*' { respond submissionSummaryInstance, [status: OK] }
    }
  }

  @Transactional
  def delete(SubmissionSummary submissionSummaryInstance) {

    if (submissionSummaryInstance == null) {
      notFound()
      return
    }

    submissionSummaryInstance.delete flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.deleted.message', args: [message(code: 'SubmissionSummary.label', default: 'SubmissionSummary'), submissionSummaryInstance.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NO_CONTENT }
    }
  }

  def answers(SubmissionSummary submissionSummaryInstance) {

  }

    protected void notFound() {
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'submissionSummary.label', default: 'SubmissionSummary'), params.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NOT_FOUND }
    }
  }
}

ipeer-web/grails-app/controllers/ipeer/webservice/SubmissionSummaryController.groovy
package ipeer.webservice

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import ipeer.entity.Role
import ipeer.entity.SubmissionSummary
import ipeer.entity.User
import ipeer.entity.Veteran

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class SubmissionSummaryController {

  static namespace = "webservice"
  static responseFormats = ['json', 'xml']
  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

  def springSecurityService

  def beforeInterceptor = {
    if(springSecurityService.authentication.authorities.any {it.authority == Role.ROLE_MENTOR}) {
      return true
    }

    def submissionSummary = SubmissionSummary.findById(params.id)
    def user = springSecurityService.currentUser as User
    if(user?.veteran != submissionSummary.veteran) {
      render(status: NOT_FOUND)
      return false
    }

    return true
  }

  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    respond SubmissionSummary.list(params), [status: OK]
  }

  @Secured(['ROLE_VETERAN', 'ROLE_MENTOR'])
  def show(SubmissionSummary submissionSummary) {
    respond submissionSummary
  }

  @Secured(['ROLE_VETERAN', 'ROLE_MENTOR'])
  def submittedAnswers(SubmissionSummary submissionSummary) {
    respond submissionSummary.submittedAnswers
  }

  @Transactional
  def save(SubmissionSummary submissionSummaryInstance) {
    if (submissionSummaryInstance == null) {
      render status: NOT_FOUND
      return
    }

    submissionSummaryInstance.validate()
    if (submissionSummaryInstance.hasErrors()) {
      render status: NOT_ACCEPTABLE
      return
    }

    submissionSummaryInstance.save flush: true
    respond submissionSummaryInstance, [status: CREATED]
  }

  @Transactional
  def update(SubmissionSummary submissionSummaryInstance) {
    if (submissionSummaryInstance == null) {
      render status: NOT_FOUND
      return
    }

    submissionSummaryInstance.validate()
    if (submissionSummaryInstance.hasErrors()) {
      render status: NOT_ACCEPTABLE
      return
    }

    submissionSummaryInstance.save flush: true
    respond submissionSummaryInstance, [status: OK]
  }

  @Transactional
  def delete(SubmissionSummary submissionSummaryInstance) {

    if (submissionSummaryInstance == null) {
      render status: NOT_FOUND
      return
    }

    submissionSummaryInstance.delete flush: true
    render status: NO_CONTENT
  }
}

ipeer-web/grails-app/views/submissionSummary/_form.gsp
<%@ page import="ipeer.entity.SubmissionSummary" %>




<div class="mdl-grid ${hasErrors(bean: submissionSummary, field: 'schedule', 'error')} required">
  <div class="mdl-cell mdl-cell--3-col">  <label for="schedule">
    <g:message code="submissionSummary.schedule.label" default="Schedule"/>
    <span class="required-indicator">*</span>
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:select id="schedule" name="schedule.id" from="${ipeer.entity.Schedule.list()}" optionKey="id" required="" value="${submissionSummary?.schedule?.id}" class="many-to-one"/>
</div>
</div>


<div class="mdl-grid ${hasErrors(bean: submissionSummary, field: 'veteran', 'error')} required">
  <div class="mdl-cell mdl-cell--3-col">  <label for="veteran">
    <g:message code="submissionSummary.veteran.label" default="Veteran"/>
    <span class="required-indicator">*</span>
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:select id="veteran" name="veteran.id" from="${ipeer.entity.Veteran.list()}" optionKey="id" required="" value="${submissionSummary?.veteran?.id}" class="many-to-one"/>
</div>
</div>


<div class="mdl-grid ${hasErrors(bean: submissionSummary, field: 'submissionTime', 'error')} required">
  <div class="mdl-cell mdl-cell--3-col">  <label for="submissionTime">
    <g:message code="submissionSummary.submissionTime.label" default="Submission Time"/>
    <span class="required-indicator">*</span>
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:datePicker name="submissionTime" precision="day"  value="${submissionSummary?.submissionTime}"  />
</div>
</div>


<div class="mdl-grid ${hasErrors(bean: submissionSummary, field: 'score', 'error')} required">
  <div class="mdl-cell mdl-cell--3-col">  <label for="score">
    <g:message code="submissionSummary.score.label" default="Score"/>
    <span class="required-indicator">*</span>
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:field name="score" type="number" value="${submissionSummary.score}" required=""/>
</div>
</div>


<div class="mdl-grid ${hasErrors(bean: submissionSummary, field: 'progressDirection', 'error')} required">
  <div class="mdl-cell mdl-cell--3-col">  <label for="progressDirection">
    <g:message code="submissionSummary.progressDirection.label" default="Progress Direction"/>
    <span class="required-indicator">*</span>
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:field name="progressDirection" type="number" value="${submissionSummary.progressDirection}" required=""/>
</div>
</div>


<div class="mdl-grid ${hasErrors(bean: submissionSummary, field: 'submittedBy', 'error')} ">
  <div class="mdl-cell mdl-cell--3-col">  <label for="submittedBy">
    <g:message code="submissionSummary.submittedBy.label" default="Submitted By"/>
    
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:select id="submittedBy" name="submittedBy.id" from="${ipeer.entity.Mentor.list()}" optionKey="id" value="${submissionSummary?.submittedBy?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>
</div>


<div class="mdl-grid ${hasErrors(bean: submissionSummary, field: 'submittedAnswers', 'error')} ">
  <div class="mdl-cell mdl-cell--3-col">  <label for="submittedAnswers">
    <g:message code="submissionSummary.submittedAnswers.label" default="Submitted Answers"/>
    
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col">
<ul class="one-to-many">
<g:each in="${submissionSummary?.submittedAnswers?}" var="s">
    <li><g:link controller="submittedAnswer" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="submittedAnswer" action="create" params="['submissionSummary.id': submissionSummary?.id]">${message(code: 'default.add.label', args: [message(code: 'submittedAnswer.label', default: 'SubmittedAnswer')])}</g:link>
</li>
</ul>

</div>
</div>

ipeer-web/grails-app/views/submissionSummary/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'submissionSummary.label', default: 'SubmissionSummary')}"/>
  <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>


<g:form class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--8-col mdl-cell--4-col-phone mdl-cell--4-col-tablet mdl-cell--8-col-desktop"
        action="save" namespace="admin" >
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.create.label" args="[entityName]"/>
  </div>

  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${submissionSummary}">
      <ul class="errors" role="alert">
      <g:eachError bean="${submissionSummary}" var="error">
        <li<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
        <g:message error="${error}"/>
        </li>
      </g:eachError>
      </ul>
    </g:hasErrors>

    <g:render template="form"/>
  </div>

  <div class="mdl-card__actions mdl-card--border">
    <g:submitButton name="create" value="${message(code: 'default.button.create.label', default: 'Create')}"
                    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white"/>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="index" namespace="admin">
      Cancel
    </g:link>
  </div>
</g:form>

</body>
</html>

ipeer-web/grails-app/views/submissionSummary/edit.gsp
<%@ page import="ipeer.entity.SubmissionSummary" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'submissionSummary.label', default: 'SubmissionSummary')}"/>
  <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>

<g:form class="mdl-card  mdl-shadow--2dp mdl-cell mdl-cell--8-col mdl-cell--4-col-phone mdl-cell--4-col-tablet mdl-cell--8-col-desktop"
        action="update" namespace="admin" resource="${submissionSummary}"
        method="PUT" >
  <g:hiddenField name="version" value="${submissionSummary?.version}"/>
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.create.label" args="[entityName]"/>
  </div>
  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${submissionSummary}">
      <ul class="errors" role="alert">
      <g:eachError bean="${submissionSummary}" var="error">
        <li<g:if
          test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
          error="${error}"/></li>
      </g:eachError>
      </ul>
    </g:hasErrors>

    <g:render template="form"/>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <g:actionSubmit class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white"
                    action="update" value="${message(code: 'default.button.update.label', default: 'Update')}"/>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="index" namespace="admin">
      Cancel
    </g:link>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="create" namespace="admin">
      <g:message code="default.new.label" args="[entityName]"/>
    </g:link>
  </div>
</g:form>

</body>
</html>

ipeer-web/grails-app/views/submissionSummary/index.gsp
<%@ page import="ipeer.entity.SubmissionSummary" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'submissionSummary.label', default: 'SubmissionSummary')}"/>
  <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-desktop  mdl-cell--8-col-tablet  mdl-cell--6-col-phone">
  <h1><g:message code="default.list.label" args="[entityName]"/></h1>
  <g:if test="${flash.message}">
    <div class="message" role="status">${flash.message}</div>
  </g:if>

  <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
    <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">
        <g:message code="submissionSummary.id.label" default="#"/>
      </th>
      
      <th class="mdl-data-table__cell--non-numeric">
        <g:message code="submissionSummary.schedule.label" default="Schedule"/>
      </th>
      
      <th class="mdl-data-table__cell--non-numeric">
        <g:message code="submissionSummary.veteran.label" default="Veteran"/>
      </th>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="submissionTime"
                        title="${message(code: 'submissionSummary.submissionTime.label', default: 'Submission Time')}"/>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="score"
                        title="${message(code: 'submissionSummary.score.label', default: 'Score')}"/>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="progressDirection"
                        title="${message(code: 'submissionSummary.progressDirection.label', default: 'Progress Direction')}"/>
      
      <th class="mdl-data-table__cell--non-numeric">
        <g:message code="submissionSummary.submittedBy.label" default="Submitted By"/>
      </th>
      
      <th class="mdl-data-table__cell--non-numeric">Action</th>
    </tr>
    </thead>
    <tbody>
    <g:each in="${submissionSummaryList}" status="i" var="submissionSummary">
      <tr>
        <td class="mdl-data-table__cell--non-numeric">
          <g:link namespace="admin" action="show" id="${submissionSummary.id}">${submissionSummary.id}</g:link>
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
            
            <g:link namespace="admin" controller="schedule" action="show" id="${submissionSummary.schedule.id}">${submissionSummary.schedule}</g:link>
            
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
            
            <g:link namespace="admin" controller="veteran" action="show" id="${submissionSummary.veteran.id}">${submissionSummary.veteran}</g:link>
            
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          <g:formatDate date="${submissionSummary.submissionTime}"/>
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          ${fieldValue(bean: submissionSummary, field: "score")}
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          ${fieldValue(bean: submissionSummary, field: "progressDirection")}
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">


            <g:if test="${submissionSummary.submittedBy != null}">
            <g:link namespace="admin" controller="mentor" action="show" id="${submissionSummary.submittedBy.id}">${submissionSummary.submittedBy}</g:link>
            </g:if>
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
          <g:link namespace="admin" action="show" id="${submissionSummary.id}"><i class="mdl-color-text--grey material-icons">description</i></g:link>
        </td>
      </tr>
    </g:each>
    </tbody>
  </table>

  <div class="mdl-card__actions pagination">
    <g:link namespace="admin" controller="veteran" action="index"
            class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white">
      Veterans
    </g:link>
    <g:paginate namespace="admin" controller="submissionSummary" action="index" total="${submissionSummaryCount ?: 0}"/>
  </div>
</div>
</body>
</html>

ipeer-web/grails-app/views/submissionSummary/show.gsp
<%@ page import="ipeer.entity.SubmissionSummary" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'submissionSummary.label', default: 'SubmissionSummary')}"/>
  <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col mdl-cell--4-col-phone">
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.show.label" args="[entityName]"/>
  </div>

  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>

    
    <g:if test="${submissionSummary?.schedule}">
      <div class="mdl-grid">
        <div id="schedule-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="submissionSummary.schedule.label" default="Schedule"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="schedule-label">
          
          <g:link controller="schedule" namespace="admin" action="show" id="${submissionSummary?.schedule?.id}">${submissionSummary?.schedule?.encodeAsHTML()}</g:link>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${submissionSummary?.veteran}">
      <div class="mdl-grid">
        <div id="veteran-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="submissionSummary.veteran.label" default="Veteran"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="veteran-label">
          
          <g:link controller="veteran" namespace="admin" action="show" id="${submissionSummary?.veteran?.id}">${submissionSummary?.veteran?.encodeAsHTML()}</g:link>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${submissionSummary?.submissionTime}">
      <div class="mdl-grid">
        <div id="submissionTime-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="submissionSummary.submissionTime.label" default="Submission Time"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="submissionTime-label">
          
          <g:formatDate date="${submissionSummary?.submissionTime}"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${submissionSummary?.score}">
      <div class="mdl-grid">
        <div id="score-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="submissionSummary.score.label" default="Score"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="score-label">
          
          <g:fieldValue bean="${submissionSummary}" field="score"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${submissionSummary?.progressDirection}">
      <div class="mdl-grid">
        <div id="progressDirection-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="submissionSummary.progressDirection.label" default="Progress Direction"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="progressDirection-label">
          
          <g:fieldValue bean="${submissionSummary}" field="progressDirection"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${submissionSummary?.submittedBy}">
      <div class="mdl-grid">
        <div id="submittedBy-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="submissionSummary.submittedBy.label" default="Submitted By"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="submittedBy-label">
          
          <g:link controller="mentor" namespace="admin" action="show" id="${submissionSummary?.submittedBy?.id}">${submissionSummary?.submittedBy?.encodeAsHTML()}</g:link>
          
        </div>
      </div>
    </g:if>

  </div>


  <g:form class="mdl-card__actions mdl-card--border" action="delete" resource="${submissionSummary}" namespace="admin" method="DELETE">
      <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" namespace="admin" controller="veteran" action="show" id="${submissionSummary.veteran.id}"><g:message code="default.list.label" args="[entityName]"/></g:link>
  </g:form>
</div>

<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-desktop  mdl-cell--8-col-tablet  mdl-cell--6-col-phone">
  <h4>Submitted Answers</h4>

  <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
    <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Question</th>
      <th class="mdl-data-table__cell--non-numeric">Answer</th>
    </tr>
    </thead>
    <tbody>
    <g:each in="${submissionSummary?.submittedAnswers}" status="i" var="submittedAnswer">
      <tr>
        <td class="mdl-data-table__cell--non-numeric">${submittedAnswer.question}</td>
        <td class="mdl-data-table__cell--non-numeric">${submittedAnswer.choice}</td>
    </g:each>
    </tbody>
  </table>
</div>

</body>
</html>