ipeer-web-legacy/ipeer-web/grails-app/domain/ipeer/entity/Survey.groovy
package ipeer.entity

class Survey {

  String title
  Boolean active

  static hasMany = [questions: Question]

  static mapping = {
    version false
  }

  static constraints = {
    title nullable: false
  }

  @Override
  String toString() {
    title
  }

}

ipeer-web-legacy/ipeer-web/grails-app/controllers/ipeer/admin/SurveyController.groovy
package ipeer.admin

import grails.plugin.springsecurity.annotation.Secured
import ipeer.entity.Survey

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(['ROLE_MENTOR'])
class SurveyController {

  static namespace = "admin"
  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    respond Survey.list(params), model: [surveyInstanceCount: Survey.count()]
  }

  def show(Survey surveyInstance) {
    respond surveyInstance
  }

  def create() {
    respond new Survey(params)
  }

  @Transactional
  def save(Survey surveyInstance) {
    if (surveyInstance == null) {
      notFound()
      return
    }

    if (surveyInstance.hasErrors()) {
      respond surveyInstance.errors, view: 'create'
      return
    }

    surveyInstance.save flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.created.message', args: [message(code: 'survey.label', default: 'Survey'), surveyInstance.id])
        redirect surveyInstance
      }
      '*' { respond surveyInstance, [status: CREATED] }
    }
  }

  def edit(Survey surveyInstance) {
    respond surveyInstance
  }

  @Transactional
  def update(Survey surveyInstance) {
    if (surveyInstance == null) {
      notFound()
      return
    }

    if (surveyInstance.hasErrors()) {
      respond surveyInstance.errors, view: 'edit'
      return
    }

    surveyInstance.save flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.updated.message', args: [message(code: 'Survey.label', default: 'Survey'), surveyInstance.id])
        redirect surveyInstance
      }
      '*' { respond surveyInstance, [status: OK] }
    }
  }

  @Transactional
  def delete(Survey surveyInstance) {

    if (surveyInstance == null) {
      notFound()
      return
    }

    surveyInstance.delete flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.deleted.message', args: [message(code: 'Survey.label', default: 'Survey'), surveyInstance.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NO_CONTENT }
    }
  }

  protected void notFound() {
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'survey.label', default: 'Survey'), params.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NOT_FOUND }
    }
  }
}

ipeer-web-legacy/ipeer-web/grails-app/controllers/ipeer/webservice/SurveyController.groovy
package ipeer.webservice

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import ipeer.entity.Survey

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class SurveyController {

  static namespace = "webservice"
  static responseFormats = ['json', 'xml']
  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

  @Secured(['ROLE_MENTOR', 'ROLE_VETERAN'])
  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    respond Survey.list(params), [status: OK]
  }

  @Secured(['ROLE_MENTOR', 'ROLE_VETERAN'])
  def show(Survey survey) {
    respond survey
  }

  @Secured(['ROLE_MENTOR', 'ROLE_VETERAN'])
  def questions(Survey survey) {
    respond survey.questions
  }

  @Transactional
  def save(Survey surveyInstance) {
    if (surveyInstance == null) {
      render status: NOT_FOUND
      return
    }

    surveyInstance.validate()
    if (surveyInstance.hasErrors()) {
      render status: NOT_ACCEPTABLE
      return
    }

    surveyInstance.save flush: true
    respond surveyInstance, [status: CREATED]
  }

  @Transactional
  def update(Survey surveyInstance) {
    if (surveyInstance == null) {
      render status: NOT_FOUND
      return
    }

    surveyInstance.validate()
    if (surveyInstance.hasErrors()) {
      render status: NOT_ACCEPTABLE
      return
    }

    surveyInstance.save flush: true
    respond surveyInstance, [status: OK]
  }

  @Transactional
  def delete(Survey surveyInstance) {

    if (surveyInstance == null) {
      render status: NOT_FOUND
      return
    }

    surveyInstance.delete flush: true
    render status: NO_CONTENT
  }
}

ipeer-web-legacy/ipeer-web/grails-app/views/survey/_form.gsp
<%@ page import="ipeer.entity.Survey" %>




<div class="mdl-grid ${hasErrors(bean: surveyInstance, field: 'title', 'error')} required">
  <div class="mdl-cell mdl-cell--3-col">  <label for="title">
    <g:message code="survey.title.label" default="Title"/>
    <span class="required-indicator">*</span>
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:textField name="title" required="" value="${surveyInstance?.title}"/>
</div>
</div>


<div class="mdl-grid ${hasErrors(bean: surveyInstance, field: 'active', 'error')} ">
  <div class="mdl-cell mdl-cell--3-col">  <label for="active">
    <g:message code="survey.active.label" default="Active"/>
    
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:checkBox name="active" value="${surveyInstance?.active}" />
</div>
</div>


<div class="mdl-grid ${hasErrors(bean: surveyInstance, field: 'questions', 'error')} ">
  <div class="mdl-cell mdl-cell--3-col">  <label for="questions">
    <g:message code="survey.questions.label" default="Questions"/>
    
  </label>
  </div>
  <div class="mdl-cell mdl-cell--3-col"><g:select name="questions" from="${ipeer.entity.Question.list()}" multiple="multiple" optionKey="id" size="5" value="${surveyInstance?.questions*.id}" class="many-to-many"/>
</div>
</div>

ipeer-web-legacy/ipeer-web/grails-app/views/survey/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'survey.label', default: 'Survey')}"/>
  <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>


<g:form class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--8-col mdl-cell--4-col-phone mdl-cell--4-col-tablet mdl-cell--8-col-desktop"
        action="save" namespace="admin" >
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.create.label" args="[entityName]"/>
  </div>

  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${surveyInstance}">
      <ul class="errors" role="alert">
      <g:eachError bean="${surveyInstance}" var="error">
        <li<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
        <g:message error="${error}"/>
        </li>
      </g:eachError>
      </ul>
    </g:hasErrors>

    <g:render template="form"/>
  </div>

  <div class="mdl-card__actions mdl-card--border">
    <g:submitButton name="create" value="${message(code: 'default.button.create.label', default: 'Create')}"
                    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white"/>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="index" namespace="admin">
      Cancel
    </g:link>
  </div>
</g:form>

</body>
</html>

ipeer-web-legacy/ipeer-web/grails-app/views/survey/edit.gsp
<%@ page import="ipeer.entity.Survey" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'survey.label', default: 'Survey')}"/>
  <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>

<g:form class="mdl-card  mdl-shadow--2dp mdl-cell mdl-cell--8-col mdl-cell--4-col-phone mdl-cell--4-col-tablet mdl-cell--8-col-desktop"
        action="update" namespace="admin" resource="${surveyInstance}"
        method="PUT" >
  <g:hiddenField name="version" value="${surveyInstance?.version}"/>
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.create.label" args="[entityName]"/>
  </div>
  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${surveyInstance}">
      <ul class="errors" role="alert">
      <g:eachError bean="${surveyInstance}" var="error">
        <li<g:if
          test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
          error="${error}"/></li>
      </g:eachError>
      </ul>
    </g:hasErrors>

    <g:render template="form"/>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <g:actionSubmit class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white"
                    action="update" value="${message(code: 'default.button.update.label', default: 'Update')}"/>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="index" namespace="admin">
      Cancel
    </g:link>
    <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" action="create" namespace="admin">
      <g:message code="default.new.label" args="[entityName]"/>
    </g:link>
  </div>
</g:form>

</body>
</html>

ipeer-web-legacy/ipeer-web/grails-app/views/survey/index.gsp
<%@ page import="ipeer.entity.Survey" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'survey.label', default: 'Survey')}"/>
  <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-desktop  mdl-cell--8-col-tablet  mdl-cell--6-col-phone">
  <h1><g:message code="default.list.label" args="[entityName]"/></h1>
  <g:if test="${flash.message}">
    <div class="message" role="status">${flash.message}</div>
  </g:if>

  <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
    <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">
        <g:message code="survey.id.label" default="#"/>
      </th>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="title"
                        title="${message(code: 'survey.title.label', default: 'Title')}"/>
      
      <g:sortableColumn namespace="admin" action="index" class="mdl-data-table__cell--non-numeric" property="active"
                        title="${message(code: 'survey.active.label', default: 'Active')}"/>
      
      <th class="mdl-data-table__cell--non-numeric">Action</th>
    </tr>
    </thead>
    <tbody>
    <g:each in="${surveyInstanceList}" status="i" var="surveyInstance">
      <tr>
        <td class="mdl-data-table__cell--non-numeric">
          <g:link namespace="admin" action="show" id="${surveyInstance.id}">${surveyInstance.id}</g:link>
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          ${fieldValue(bean: surveyInstance, field: "title")}
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
        
          
          <g:formatBoolean boolean="${surveyInstance.active}"/>
          
        </td>
        
        <td class="mdl-data-table__cell--non-numeric">
          <g:link namespace="admin" action="show" id="${surveyInstance.id}"><i class="mdl-color-text--grey material-icons">description</i></g:link>
          <g:link namespace="admin" action="edit" id="${surveyInstance.id}"><i class="mdl-color-text--grey material-icons">edit</i></g:link>
        </td>
      </tr>
    </g:each>
    </tbody>
  </table>

  <div class="mdl-card__actions pagination">
    <g:link action="create" namespace="admin"
            class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green-700 mdl-color-text--white">
      <g:message code="default.new.label" args="[entityName]"/>
    </g:link>
    <g:paginate namespace="admin" controller="survey" action="index" total="${surveyInstanceCount ?: 0}"/>
  </div>
</div>
</body>
</html>

ipeer-web-legacy/ipeer-web/grails-app/views/survey/show.gsp
<%@ page import="ipeer.entity.Survey" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="dashboard">
  <g:set var="entityName" value="${message(code: 'survey.label', default: 'Survey')}"/>
  <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col mdl-cell--4-col-phone">
  <div class="mdl-card__title mdl-shadow--2dp">
    <g:message code="default.show.label" args="[entityName]"/>
  </div>

  <div class="mdl-card__supporting-text">
    <g:if test="${flash.message}">
      <div class="message" role="status">${flash.message}</div>
    </g:if>

    
    <g:if test="${surveyInstance?.title}">
      <div class="mdl-grid">
        <div id="title-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="survey.title.label" default="Title"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="title-label">
          
          <g:fieldValue bean="${surveyInstance}" field="title"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${surveyInstance?.active}">
      <div class="mdl-grid">
        <div id="active-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="survey.active.label" default="Active"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="active-label">
          
          <g:formatBoolean boolean="${surveyInstance?.active}"/>
          
        </div>
      </div>
    </g:if>
    
    <g:if test="${surveyInstance?.questions}">
      <div class="mdl-grid">
        <div id="questions-label" class="mdl-cell mdl-cell--4-col">
          <g:message code="survey.questions.label" default="Questions"/>
        </div>
        <div class="mdl-cell mdl-cell--4-col" aria-labelledby="questions-label">
          
          <g:each in="${surveyInstance.questions}" var="q">
            <g:link controller="question" namespace="admin" action="show" id="${q.id}">${q?.encodeAsHTML()}</g:link>
          </g:each>
          
        </div>
      </div>
    </g:if>
    
  </div>


  <g:form class="mdl-card__actions mdl-card--border" action="delete" resource="${surveyInstance}" namespace="admin" method="DELETE">
      <g:link action="edit" namespace="admin" resource="${surveyInstance}"
              class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
        <g:message code="default.button.edit.label" default="Edit"/>
      </g:link>
      <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" namespace="admin" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link>
      <g:link class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" namespace="admin" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link>
  </g:form>
</div>

</body>
</html>